### ISSUE TITLE
Usage from the host

### ISSUE THREAD

**Issue by greg0ire** [cgswong/docker-vault#11]
I suppose once you're running the container, you still have to type long lines like this to run every vault command : `docker exec vault-server vault version`. What is the recommended way to run vault from the host? Creating an alias, like `alias vault="docker exec vault-server vault"` ? Or maybe running vault directly on the guest, with `docker exec -it vault-server /bin/bash` ?

**Comment by greg0ire** [comment]
ping @cgswong

**Comment by cgswong** [comment]
A bit opinionated, but if you're on a client then I'd go the route of using an alias as it's cleaner. Just pull the image during provisioning (definitely before trying to use it anyways) so it's available. I'm doing this on CoreOS. If you're dealing with the server-side then `docker exec -it` route.

**Comment by greg0ire** [comment]
Thanks for your answer. What do you mean by a client? I'm using vault on a virtual machine on which my team can ssh.

**Comment by cgswong** [comment]
My team is using Vault in an [HA configuration](https://www.vaultproject.io/docs/concepts/ha.html) in the [client/server model](https://www.vaultproject.io/intro/getting-started/dev-server.html) so we have a Vault server that's always on and Vault clients which of course just interact with the server as needed.

**Comment by greg0ire** [comment]
Oh ok now I get it. Thanks for everything!
