### ISSUE TITLE
Possible to get mlock working?

### ISSUE THREAD

**Issue by F21** [cgswong/docker-vault#4]
When using this docker image, I get an error regarding `mlock`:

```
Error initializing core: Failed to lock memory: cannot allocate memory

This usually means that the mlock syscall is not available.
Vault uses mlock to prevent memory from being swapped to
disk. This requires root privileges as well as a machine
that supports mlock. Please enable mlock on your system or
disable Vault from using it. To disable Vault from using it,
set the `disable_mlock` configuration option in your configuration
file.
```

It's probably due to alpine linux. I am not very familiar with alpine linux, but what needs to be done to get mlock working?

**Comment by tyamell** [comment]
Just add --cap-add IPC_LOCK to your docker run statement and mlock should work

**Comment by cgswong** [comment]
@F21 The comment from @tyamell should resolve your issue as it is what I've been using for a few other images.

**Comment by F21** [comment]
Thanks guys! It works! :smile:
