### ISSUE TITLE
0.3.0 is out

### ISSUE THREAD

**Issue by johnjelinek** [cgswong/docker-vault#8]
Can you add 0.3.0?

**Comment by kpettijohn** [comment]
Just a note on 0.3.0.

I was running into issues getting `alpine:latest` to recognize the vault 0.3.0 binary.

```
sh: /usr/local/bin/vault not found
```

Something with Alpine linux using [musl](http://www.musl-libc.org) and how the glibc go binary was compiled I believe.

I was able to get things working by running the vault binary using the following:

```
/lib/ld-musl-x86_64.so.1 /usr/local/bin/vault
```

**Comment by jefferai** [comment]
See https://groups.google.com/forum/#!topic/vault-tool/0JCmzvk6DYA

**Comment by kpettijohn** [comment]
@jefferai thanks for the link!

**Comment by cgswong** [comment]
I'll be releasing 0.3.1 early this week,

**Comment by cgswong** [comment]
v0.3.1 has been released.
